---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  default.conf: |
    server {
        listen 80 default_server;
        server_name _;
        defaul_type text/plain;
        location / {
            return 200 '$hostname\nOK\n';
        }
    }
