---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user
roleRef:
  name: view
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: user
  namespace: default
